services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    volumes:
      - /Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
      #- /home/mediaserver/app/dashboard:/usr/share/caddy/dashboard:ro
    networks:
      - proxy-public

volumes:
  caddy-data:
    name: caddy-data
  caddy-config:
    name: caddy-config

networks:
  proxy-public:
    external: true
