services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
      - mediaserver-dashboard:/usr/share/caddy/mediaserver:ro
    networks:
      - proxy-public

volumes:
  caddy-data:
    name: caddy-data
  caddy-config:
    name: caddy-config
  mediaserver-dashboard:
    external: true
    name: mediaserver-dashboard

networks:
  proxy-public:
    external: true
