name: Deploy infra
on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  deploy:
    environment: Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload repo via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "." # tutto il repo
          target: "/opt/core-server" # cartella destinazione
          rm: true # opzionale: pulisci target prima
          overwrite: true

      - name: Write .env
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            set -Eeuo pipefail
            cd /opt/core-server

            rm -rf cloudflared/.env
            touch cloudflared/.env
            printf '%s\n' "${{ secrets.CLOUDFLARED_TUNNEL_TOKEN }}" > cloudflared/.env

            ./scripts/cli.sh up
